#18 Añadir documentacion para usar la app
EstandaresDeCalidadSW23/amiguitosvisibles pull request #19
Opened 2023-08-19 21:54 UTC by CarlosMoriel

Se añade documentación para iniciar la app mediante una wallet de phantom

2023-08-23 21:19 UTC, bcisneros commented on README.md
> +Necesitamos una wallet (Cartera digital) para poder tener hacer transacciones
No queda claro este párrafo.

```suggestion
Necesitamos una wallet (Cartera digital) para poder hacer transacciones.
```

2023-08-23 21:19 UTC, bcisneros commented on README.md
> +- Instalamos la extinción del navegador (funciona para cualquier navegador basado en Chrome)
```suggestion
- Instalamos la extensión del navegador (funciona para cualquier navegador basado en Chrome) 
```

2023-08-23 21:20 UTC, bcisneros commented on README.md
> +![Extenciones](docs-images/2.png)
```suggestion
![Extensiones](docs-images/2.png)
```

2023-08-23 21:21 UTC, bcisneros commented on README.md
> +- IMPORTANTE para asegurar la billetera tenemos que guardar ya sea en una foto o en un archivo de texto la Fase Secreta de recuperación, es muy importante guardarla bien para que no se nos pierda la
```suggestion
> IMPORTANTE para asegurar la billetera tenemos que guardar ya sea en una foto o en un archivo de texto la Fase Secreta de recuperación, es muy importante guardarla bien para que no se nos pierda la wallet 
```

2023-08-23 21:22 UTC, bcisneros commented on README.md
> +una vez instalado yarn ejecutaremos un comando dentro del proyecto de amiguitos visibles para ello podemos usar los comandos de navegación básicos en Windows (cd, ls)
```suggestion
Una vez instalado yarn ejecutaremos un comando dentro del proyecto de amiguitos visibles para ello podemos usar los comandos de navegación básicos en Windows (cd, ls)
```

2023-08-23 21:24 UTC, bcisneros requested changes
Algunos ajustes en el texto, pero se ve bien y completo. Muchas gracias Carlos!

2023-08-25 01:19 UTC, CarlosMoriel commented
Fixed 👍

2023-08-25 01:20 UTC, bcisneros approved these changes
lgtm

2023-08-28 21:01 UTC, merged